/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packageproject;

import static com.sun.xml.internal.ws.policy.sourcemodel.wspolicy.XmlToken.Name;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M e t r o
 */
public class JFrame_save extends javax.swing.JFrame {

    private String Item;

    /**
     * Creates new form JFrame_save
     */
    public JFrame_save() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Total = new javax.swing.JLabel();
        ItemTotal = new javax.swing.JTextField();
        Item_Name = new javax.swing.JLabel();
        ItemName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Item_Price = new javax.swing.JLabel();
        ItemPrice = new javax.swing.JTextField();
        Count = new javax.swing.JLabel();
        ItemCount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Total.setText("Total");

        ItemTotal.setName("namec"); // NOI18N
        ItemTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemTotalActionPerformed(evt);
            }
        });

        Item_Name.setText("Item_Name");

        ItemName.setName("namea"); // NOI18N
        ItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemNameActionPerformed(evt);
            }
        });

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Item_Price.setText("Item_Price");

        ItemPrice.setName("nameb"); // NOI18N

        Count.setText("Count");

        ItemCount.setName("namec"); // NOI18N
        ItemCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemCountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Item_Name)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Item_Price)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Total)
                                    .addComponent(Count))))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ItemName)
                            .addComponent(ItemPrice)
                            .addComponent(ItemCount)
                            .addComponent(ItemTotal))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButton1)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Item_Name)
                    .addComponent(ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Item_Price)
                    .addComponent(ItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Count))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Total))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItemTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemTotalActionPerformed

    private void ItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        String Label7=invoiceform.jLabel7.getText().trim();
        String Item_Name= ItemName.getText().trim();
        String Item_Price= ItemPrice.getText().trim();
        String Item_Count= ItemCount.getText().trim();
        String Item_Total= ItemTotal.getText().trim();
        

        String st[]={Label7,Item_Name,Item_Price,Item_Count,Item_Total};

        invoiceform.AddRowToJtable2(st);
        JOptionPane.showMessageDialog(this,"Add Data Successfully");
        
        
            
     /*   String lb7= invoiceform.jLabel7.getText().trim();
        String txt1= invoiceform.jTextField1.getText().trim();
        String txt2= invoiceform.jTextField2.getText().trim();
        String lb9= invoiceform.jLabel9.getText().trim();
        
        String st2[]={lb7,txt1,txt2,lb9};     
        
        
         invoiceform.AddRowToJtable(st2);
         JOptionPane.showMessageDialog(this,"Add Data Successfully");
         
         DefaultTableModel model=(DefaultTableModel)invoiceform.table.getModel();
    
            if(invoiceform.table.getSelectedRowCount()==1){
            
            model.removeRow(invoiceform.table.getSelectedRow());}*/
            
        
             DefaultTableModel model=(DefaultTableModel)invoiceform.table.getModel();
              if(invoiceform.table.getSelectedRowCount()==1){
                   String lb7= invoiceform.jLabel7.getText().trim();
                    String txt1= invoiceform.jTextField1.getText().trim();
                    String txt2= invoiceform.jTextField2.getText().trim();
                    String lb9= invoiceform.jLabel9.getText().trim();
        
                  model.setValueAt(lb7,invoiceform.table.getSelectedRow(),0);
                   model.setValueAt(txt1,invoiceform.table.getSelectedRow(),1);
                    model.setValueAt(txt2,invoiceform.table.getSelectedRow(),2);
                     model.setValueAt(lb9,invoiceform.table.getSelectedRow(),3);
                     
                     JOptionPane.showMessageDialog(this, "Update succeccfully");
                     
              }else {
                  
                   if(invoiceform.table.getSelectedRowCount()==0){
                      JOptionPane.showMessageDialog(this, "Table is Empty");
                   }else{
                   
                              JOptionPane.showMessageDialog(this, "Please Select single Roew TO Save Change");
                   
                   }
              }
                  
          

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ItemCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemCountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_save.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_save.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_save.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_save.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_save().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Count;
    private static javax.swing.JTextField ItemCount;
    private static javax.swing.JTextField ItemName;
    private static javax.swing.JTextField ItemPrice;
    private static javax.swing.JTextField ItemTotal;
    private javax.swing.JLabel Item_Name;
    private javax.swing.JLabel Item_Price;
    private javax.swing.JLabel Total;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
